### ISSUE TITLE
ADL mit Fachführung klären

### ISSUE THREAD

**Issue by StephanieFrancke** [SchweizerischeBundesbahnen/DAS#197]
# Ausgangslage
Die Fachführung ZFR möchte zum Thema ADL nochmals Input geben, da sie hier in der Vergangenheit viel Zeit investiert haben.
# Weiterführende Links
--
# Out of Scope
- Allfällige weiterführende Analysen oder Umsetzungen.
# Akzeptanzkriterien
- ein Termin mit Fachführung ZFR ist aufgesetzt: 12.09.
- Inputs sind aufgenommen und das weitere Vorgehen ist definiert

**Comment by EverheardofUX** [comment]
@StephanieFrancke Meeting mit Felix und Jürg am 12.09 am Morgen aufgesetzt.
