### ISSUE TITLE
Backend Projekt aufsetzen

### ISSUE THREAD

**Issue by Grodien** [SchweizerischeBundesbahnen/DAS#52]
# Ausgangslage
Für den Durchstich benötigen wir ein Spring Boot Backend, welches auf einem SBB Openshift Cluster deployt wird. 

# Weiterführende Links
...
# Out of Scope
...
# Akzeptanzkriterien
- Backend Projekt ist aufgesetzt
- Docker Image wird gebaut
- Image wird auf SBB Openshift deployed

**Comment by kirill1722** [comment]
ist das backend bereits aufgesetzt?
