### ISSUE TITLE
Hauptsignale, Streckenausrüstung, Bahnhofsgeschwindigkeiten und Kurven

### ISSUE THREAD

**Issue by StephanieFrancke** [SchweizerischeBundesbahnen/DAS#82]
# Ausgangslage
Als Lokpersonal oder Beobachter möchte ich Hauptsignale, Streckenausrüstung und Systemübergänge, Bahnhofsgeschwindigkeiten sowie Kurven sehen, damit ich den Fahrverlauf nachvollziehen kann.
# Weiterführende Links
Figma PDF Fachgruppe: 

[82_Hauptsignale, Streckenausrüstung, Bahnhofsgeschwindigkeiten und Kurven.pdf](https://github.com/user-attachments/files/23622642/82_Hauptsignale.Streckenausrustung.Bahnhofsgeschwindigkeiten.und.Kurven.pdf)

# Out of Scope
- https://github.com/SchweizerischeBundesbahnen/DAS/issues/136
- https://github.com/SchweizerischeBundesbahnen/DAS/issues/226
- https://github.com/SchweizerischeBundesbahnen/DAS/issues/225
- https://github.com/SchweizerischeBundesbahnen/DAS/issues/224
- https://github.com/SchweizerischeBundesbahnen/DAS/issues/223
- https://github.com/SchweizerischeBundesbahnen/DAS/issues/89
- https://github.com/SchweizerischeBundesbahnen/DAS/issues/230
- https://github.com/SchweizerischeBundesbahnen/DAS/issues/231

# Akzeptanzkriterien
Es werden folgende Informationen gemäss Vorschriften dargestellt:
- Hauptsignale
  - Typ
    - Block
    - Spurwechsel
    - Deckungssignal
    - Einfahrsignal
    - Ausfahrsignal
    - Abschnittsignal
    - Sollte ein Signal mehrere mögliche Typen haben, weil er je nach Fahrt variieren kann, dann wird dies entsprechend gekennzeichnet. 
      - Ergänzung aus der Fachgruppe vom 26.09.24: Bei einem uneindeutigen Signaltypen sollen alle Signaltypen angezeigt werden.
  - Identifikator gemäss Anschrift an Signal (Visual Identifier)
  - ~~Name des Signals, sofern vorhanden (z.B. Glanzenberg)~~
  - Position
  - Kilometrierung
- Streckenausrüstung und Systemübergänge
  - Typ der Streckenausrüstung
    1. zweigleisige Strecke mit Einrichtung für Einspurbetrieb
    2. ~~zweigleisige Strecke mit Einrichtung für Einspurbetrieb und quittungspflichtiger Verständigung des LF für Fahrt auf dem rechten Gleis~~
    3. ~~zweigleisige Strecke ohne Einrichtung für Einspurbetrieb~~
    4. Strecke mit FSS im konventionellen Geschwindigkeitsbereich. «Reversing» nicht möglich
    5. Strecke mit FSS, Grenze zwischen konventionellem und erweitertem Geschwindigkeitsbereich
    6. Strecke mit FSS im erweiterten Geschwindigkeitsbereich. «Reversing» möglich
    7. Strecke mit FSS im erweiterten Geschwindigkeitsbereich. «Reversing» nicht möglich
  - Position des Systemübergangs (CAB Start und Ende)
  - Kilometrierung der Streckenausrüstungsgrenze
- Bahnhofsgeschwindigkeiten und abgestufte Geschwindigkeiten
  - Einfahrgeschwindigkeit(en) (nur relevante für die befahrene Strecke)
  - Ausfahrgeschwindigkeit(en) (nur relevante für die befahrene Strecke)
  - Gleisspezifische oder gleisgruppenspezifische Geschwindigkeiten (unabhängig davon, ob sie befahren werden)
  - ~~Kilometrierung für abgestufte Bahnhofsgeschwindigkeiten (sofern vorhanden)~~ (wurde in #231 ausgelagert)
  - Formatierungen zu den Fahrbegriffen werden gemäss RADN dargestellt
- Kurven 
  - Position
  - allfälliger Zusatz (z.B. "Ausfahrt" oder "nach Haltestelle")

# Testszenarien
## Vorbedingung:
- ~~Die fiktive Zugnummer 1234 hat folgende Streckenausrüstungen:~~
  - ~~von Betriebspunkt A nach Betriebspunkt B: zweigleisige Strecke mit Einrichtung für Einspurbetrieb und quittungspflichtiger Verständigung des LF für Fahrt auf dem rechten Gleis~~
  - ~~von Betriebspunkt B nach Betriebspunkt C: zweigleisige Strecke ohne Einrichtung für Einspurbetrieb~~

## Durchführung:
- Die Zugnummer 19166 von SBBP wird geöffnet und hat auf dem Abschnitt von Zürich HB bis Dietikon folgende Hauptsignale:
  - Abschnitt Ausfahrsignal, X16 bei km 0.4
  - Abschnitt Ausfahrsignal T(L10) bei km 0.9
  - Ausfahrsignal W20 bei km 1.2
  - Einfahrsignal A700 bei km 1.5
  - Ausfahrsignal C5 bei km 2.1
  - Spurwechsel Q702 bei km 2.7
  - Einfahrsignal B703 bei km 3.2
  - Abschnitt Einfahrsignal G347 bei km 3.7
  - Abschnitt Ausfahrsignal J547 bei km 4.3
  - Ausfahrsignal L557 bei km 4.7
  - Einfahrsignal H704 bei km 5.8
  - Abschnitt Einfahrsignal A26 bei km 6.7
  - Ausfahrsignal D6 bei km 7.8
  - Blocksignal Q9 bei km 8.9
  - Einfahrsignal A16 bei km 10.030
- Die Zugnummer 6425 von BLSP wird geöffnet.
  - Bei km 19.5 wird das Deckungssignal A dargestellt.
- Die Zugnummer 513 von SBBP wird geöffnet.
  - bei km 78.9 wird ein CAB Start dargestellt
  - bei km 54.5 wird ein CAB Ende dargestellt
  - von Elgg bei km 126.1 bis Sirnach bei km 113.8 wird die Streckenausrüstung "zweigleisige Strecke mit Einrichtung für Einspurbetrieb" dargestellt
  - von CAB Start bei km 78.9 bis CAB Ende bei km 54.5 wird die Streckenausrüstung "Strecke mit FSS im erweiterten Geschwindigkeitsbereich. «Reversing» nicht möglich" dargestellt
- Die Zugnummer 9116 von ZB wird geöffnet.
  - von Meiringen bei km 0.10 bis Innertkirchen bei km 5.0 wird die Streckenausrüstung "einspurige Strecke ohne Block" dargestellt
- Die Zugnummer 307 von SBBP wird geöffnet.
  - bei km 21.5 und 152.2 wird ein CAB Start dargestellt
  - bei km 146.8 und 179,6 wird ein CAB Ende dargestellt
  - von CAB Start bei km 21.5 bis km 36.3 wird die Streckenausrüstung "Strecke mit FSS im konventionellen Geschwindigkeitsbereich. «Reversing» nicht möglich" dargestellt
  - von Giustizia bei km 164.0 bis CAB Ende bei km 146.8 wird die Streckenausrüstung "Strecke mit FSS im konventionellen Geschwindigkeitsbereich. «Reversing» nicht möglich" dargestellt
  - von Vezia (bif) bei km 177.8 bis CAB Ende bei km 179,6 wird die Streckenausrüstung "Strecke mit FSS im konventionellen Geschwindigkeitsbereich. «Reversing» nicht möglich" dargestellt
  - bei km 36.3 wird die Streckenausrüstung "Strecke mit FSS, Grenze zwischen konventionellem und erweitertem Geschwindigkeitsbereich" dargestellt
  - von km 36.3 bis Pollegio bei km 159.0 wird die Streckenausrüstung "Strecke mit FSS im erweiterten Geschwindigkeitsbereich. «Reversing» möglich" dargestellt
  - von Camorino bei km 226.6 bis Vezia (bif) bei km 177.8 wird die Streckenausrüstung "Strecke mit FSS im erweiterten Geschwindigkeitsbereich. «Reversing» möglich" dargestellt
  - von Pollegio bei km 159.0 bis Giustizia bei km 164.0 wird die Streckenausrüstung "Strecke mit FSS im erweiterten Geschwindigkeitsbereich. «Reversing» nicht möglich" dargestellt
- ~~Die fiktive Zugnummer 1234 wird geöffnet.~~
  - ~~von Betriebspunkt A nach Betriebspunkt B wird die Streckenausrüstung "zweigleisige Strecke mit Einrichtung für Einspurbetrieb und quittungspflichtiger Verständigung des LF für Fahrt auf dem rechten Gleis" dargestellt~~
  - ~~von Betriebspunkt B nach Betriebspunkt C wird die Streckenausrüstung "zweigleisige Strecke ohne Einrichtung für Einspurbetrieb" dargestellt~~
- Die Zugnummer 2926 von ZB wird geöffnet. Es werden folgende Kurven dargestellt:
  - Kurve bei km 7.1
  - Kurve nach Haltestelle bei km 7.3
  - Kurve bei km 9.9
  - Kurve bei km 14.4
  - Kurve Ausfahrt bei km 15.4
  - Kurve bei km 22.3
  - Kurve Ausfahrt bei km 24.1
  - Kurve nach Haltestelle bei km 25.5
  - Kurve Ausfahrt bei km 45.9
  - Kurve bei km 55.5
  - Kurve Ausfahrt bei km 58.
  - Kurve bei km 72.7
- Die Zugnummer 2461 von SBBP wird geöffnet.
  - Beim Betriebspunkt Basel SBB wird zum Gleis 4 eine Gleisspezifische Geschwindigkeit dargestellt.
- Die Zugnummer 16353 von BLSP wird geöffnet.
  - Beim Klick auf die Bahnhofsgeschwindigkeiten von Weissenbühl werden folgende Informationen angezeigt:
    - 90/85: Ein- und Ausfahrt Seite Wabern: Geschwindigkeitsschwelle ab/bis „Merktafel für Änderung der Höchstgeschwindigkeit“ bei km 5.4
  - Beim Klick auf die Bahnhofsgeschwindigkeiten von Bern werden folgende Informationen angezeigt: 
    -  80/75: Ausfahrt Seite Weyermannshaus ab Ausfahrsignal, wenn an diesem freie Fahrt signalisiert wird.
    - 80/75:  Ausfahrt Seite Bern Wyler ab „Merktafel für Änderung der Höchstgeschwindigkeit“ bei km 105.9 wenn an Signalstaffel D freie Fahrt signalisiert wird

**Comment by mghilardelli** [comment]
@StephanieFrancke 

> * Bahnübergangsüberwachungsbalisen
>   * Position (korrekte Eingliederung in die Betriebspunktabfolge, siehe https://github.com/SchweizerischeBundesbahnen/DAS/issues/81)
>   * Anzahl der durch die jeweilige Balise überwachten Bahnübergänge
>   * Anzahl der Balisen

Gemäss Dani bekommen wir pro Balise die beiden ersten Infos. Was ist denn noch mit `Anzahl der Balisen` gemeint?

**Comment by mghilardelli** [comment]
@StephanieFrancke Ich würde es bevorzugen die AKs der Kilometrierung bei den jeweiligen Themen zu integrieren, erledigt ein wenig die Redundanz

**Comment by EverheardofUX** [comment]
@StephanieFrancke @Grodien @mghilardelli 
Aus UX Sicht wird die Story sehr gross, ich werde sie also in 6 verschiedenen Story schneiden je nach Darstellung Bereich (und je nachdem, was wir schon abgeklärt haben oder nicht). Die Story sind wie folgt geschnitten: 

Story 1: 
- Hauptsignale
Typ (Block, Spurwechsel, Deckungssignal, Einfahrsignal, Ausfahrsignal, Abschnittsignal) (die Signaltypen sind optisch unterscheidbar)
Signalbezeichnung
Position (korrekte Eingliederung in die Betriebspunktabfolge, siehe https://github.com/SchweizerischeBundesbahnen/DAS/issues/81)
- Streckenausrüstung und Systemübergänge
Typ der Streckenausrüstung
Position des Systemübergangs (korrekte Eingliederung in die Betriebspunktabfolge, siehe https://github.com/SchweizerischeBundesbahnen/DAS/issues/81)
- Kurven
Position (korrekte Eingliederung in die Betriebspunktabfolge, siehe https://github.com/SchweizerischeBundesbahnen/DAS/issues/81)
- Weichen
Position (korrekte Eingliederung in die Betriebspunktabfolge, siehe https://github.com/SchweizerischeBundesbahnen/DAS/issues/81)

Story 2: Schützstrecken

Story 3: Bahnüberwachungbalisen - Strassenbahnbereiche (Vermutlich bleibt länger in Backlog da wir in Testings Schwierigkeiten festgestellt haben - Stand 09.08.2024) 

Story 4: Kilometrierung & Km Tafeln 

Story 5: Massgebende Neigung - Noch zu prüfen, bleibt länger in Backlog (Stand 09.08.2024) 

Story 6: Netzwechseln & Abfahrterlaubnis 

Alle die Story werde ich neu erstellen (indem ich diese kopiere) - am Ende können wir die übergreifende Story abschliessen bzw. löschen. Ich hoffe es passt.

**Comment by mghilardelli** [comment]
@EverheardofUX Finde ich gut. Kannst du gleich noch den Vorschlag integrieren, dass die Kilometrierung in die jeweiligen anderen Storys integriert werden. Story 4 wär dann nur `Km Tafeln` und die Kilometrierungen in den anderen Storys ergänzt

**Comment by StephanieFrancke** [comment]
> @StephanieFrancke
> 
> > * Bahnübergangsüberwachungsbalisen
> >   
> >   * Position (korrekte Eingliederung in die Betriebspunktabfolge, siehe [Betriebspunktabfolge #81](https://github.com/SchweizerischeBundesbahnen/DAS/issues/81))
> >   * Anzahl der durch die jeweilige Balise überwachten Bahnübergänge
> >   * Anzahl der Balisen
> 
> Gemäss Dani bekommen wir pro Balise die beiden ersten Infos. Was ist denn noch mit `Anzahl der Balisen` gemeint?

Hoi @mghilardelli 
Gemäss Besprechung mit Dani Minder werden wir uns selber um eine allfällige Konsolidierung kümmern. Die Balisen werden daher immer einzeln gesendet. Ich habe die Angabe "Anzahl der Balisen" entfernt.

**Comment by StephanieFrancke** [comment]
> @StephanieFrancke
> 
> * Ich würde es bevorzugen die AKs der Kilometrierung bei den jeweiligen Themen zu integrieren, erledigt ein wenig die Redundanz

Passt so für mich, ich werde es entsprechend auftrennen.

> * Was für Infos brauchts bei `Massgebende Neigung` ausser die Position? Steigung und Gefälle?

Ja, Steigung/Gefälle hat noch gefehlt, ich habe es ergänzt. Mehr als das sollte es nicht brauchen.

> * Kurven: Da steht nur Position, ich nehme an es geht aber vor Allem um die Geschwindigkeit? Andere Kurven hätten wir auch nicht auf der Schnittstelle

Die Geschwindigkeit der Kurve ist von der ausgewählten Zug- und Bremsreihe abhängig und daher in https://github.com/SchweizerischeBundesbahnen/DAS/issues/89 integriert. Ich bin aber offen, falls ihr die Stories anders schneiden möchtet.

> * Bei der Kilometrierung steht `Weichen auf der Strecke` sowie `Anschlussgleise`. Ist das so wirklich gewollt. Mit einer Weiche auf der Strecke, was gemäss Dani dasselbe wie eine Anschlussweiche ist, kommt man ja in ein Anschlussgleis.

Gemäss Besprechung mit Dani: Mit Weiche ist immer eine Anschlussweiche gemeint. Leider gibt es aber auch Anschlussgleise in RADN ohne Weiche, daher lasse ich die beiden Infos separat.

**Comment by StephanieFrancke** [comment]
Hoi @EverheardofUX und @mghilardelli 

Ich habe die Story wie folgt aufgeteilt:
#136 
#226 
#225 
#224 
#223 

Die Kilometrierungen habe ich in die entsprechenden User Stories verteilt.
Gebt mir Bescheid, falls für euch etwas noch nicht stimmig ist.

**Comment by mghilardelli** [comment]
@EverheardofUX Sind die Bahnhofsgeschwindikeiten hier schon ready oder soll das erst später kommen?

**Comment by EverheardofUX** [comment]
Hallo @StephanieFrancke 
das hier:
"Zusätzliche Akzeptanzkriterien:

Bei den Bahnhofsgeschwindigkeiten können - sofern vorhanden - weitere Details zu den Geschwindigkeitsschwellen (in Textform) aufgerufen werden."

Würde ich hier Out of Scope setzen und in eine neue Story platzieren da es geht um aufrufbares Infos. Merci merci :)

**Comment by EverheardofUX** [comment]
> [@EverheardofUX](https://github.com/EverheardofUX) Sind die Bahnhofsgeschwindikeiten hier schon ready oder soll das erst später kommen? @mghilardelli 

Die können hier in Spalte rechts ergänzt werden. Formatierung wird zunächst angepasst und am graphische oder tabellarische Darstellung adaptiert. passt für dich?

**Comment by EverheardofUX** [comment]
@Grodien @mghilardelli @StephanieFrancke Bitte Prüfen, falls OK ready für Abnahme FG.

**Comment by mghilardelli** [comment]
Für mich noch unklar
* abgestufte Geschwindigkeiten
* Darstellung der verschiedenen Signale (z. B. Spurwechsel)

**Comment by StephanieFrancke** [comment]
Hoi @EverheardofUX 
Ich habe die Anforderung wie folgt angepasst: Neu zeigen wir bei den Signalen "Identifikator gemäss Anschrift an Signal (Visual Identifier)" anstatt die Namen (z.B. Glanzenberg). Passt das so für dich?

**Comment by i002423** [comment]
- Die alten Blockbezeichnungen "Glanzberg" sind veraltet, haben aber eine gewisse Tradition und werden zum Teil von alten Fdl noch verwendet. Es wäre schön wenn wir diese Beizeichnungen noch verwenden könnten. Siehe Anhang

![Uploading Bild1.png…]()

**Comment by i002423** [comment]
![Bild1](https://github.com/user-attachments/assets/29d44f81-8540-4ee9-a2fb-0190e9014274)

**Comment by StephanieFrancke** [comment]
> * Name des Signals, sofern vorhanden (z.B. Glanzenberg)

Hoi @i002423 
Ich habe dies entsprechend wieder in den Akzeptanzkriterien ergänzt:
"Name des Signals, sofern vorhanden (z.B. Glanzenberg)"

Aus meiner Sicht sollten wir das zusätzlich anzeigen können. 
@EverheardofUX : Für dich zur Info und damit du allenfalls ein Veto geben kannst.

**Comment by Mathieu-Ochsenbein** [comment]
> Wie bereits in kleiner Runde kürzlich diskutiert, müssen wir uns genau überlegen, ob man auch die Abschnittssignale anzeigen möchte und falls ja, wie man die Signale ganz generell bezeichnet. Da es diverse komplexe Betriebspunkte gibt, an welchem je nach Fahrweg ein Signal nicht immer dieselbe Bedeutung hat. Zudem ist die Bezeichnung der jeweiligen Funktion nicht immer eindeutig und immer auch sehr davon abhängig, welcher Personenkreis dies diskutiert und anschliessend festlegt. Blocksignale sind diesbezüglich am einfachsten und sollten auf jeden Fall auch als solche Bezeichnet werden (analog heute).

1) Als Ergänzung, je nach Bahnhof kann die Anzahl der Abschnitte je nach Spur unterschiedlich sein. 
2) Im Fall eine Anpassung der Abschnitte muss der DAS sofort die Anpassung haben. Insbesondere für ein Eingang Abschnitt.

**Comment by StephanieFrancke** [comment]
> > Wie bereits in kleiner Runde kürzlich diskutiert, müssen wir uns genau überlegen, ob man auch die Abschnittssignale anzeigen möchte und falls ja, wie man die Signale ganz generell bezeichnet. Da es diverse komplexe Betriebspunkte gibt, an welchem je nach Fahrweg ein Signal nicht immer dieselbe Bedeutung hat. Zudem ist die Bezeichnung der jeweiligen Funktion nicht immer eindeutig und immer auch sehr davon abhängig, welcher Personenkreis dies diskutiert und anschliessend festlegt. Blocksignale sind diesbezüglich am einfachsten und sollten auf jeden Fall auch als solche Bezeichnet werden (analog heute).
> 
> 1. Als Ergänzung, je nach Bahnhof kann die Anzahl der Abschnitte je nach Spur unterschiedlich sein.
> 2. Im Fall eine Anpassung der Abschnitte muss der DAS sofort die Anpassung haben. Insbesondere für ein Eingang Abschnitt.

Hoi @Mathieu-Ochsenbein 
Merci vielmals für deine Ergänzungen.
Die Abschnittsignale werden gleisgenau gesendet und bei einem Gleiswechsel auch entsprechend geändert. Ob diese Genauigkeit und auch der Wechsel ausreichend verstanden wird, muss noch in den Tests mit Lokführern gut geprüft werden. Aktuell steht auch zur Diskussion, die Abschnittsignale ausblenden zu können.

**Comment by StephanieFrancke** [comment]
Aufgrund von einem Entscheid des Kernteams vom 04.11. wurde folgender Teil der Akzeptanzkriterien gestrichen:
- "Name des Signals, sofern vorhanden (z.B. Glanzenberg)"

**Comment by StephanieFrancke** [comment]
Aufgrund von einem Entscheid des Kernteams vom 12.11. wurde folgender Teil der Akzeptanzkriterien gestrichen, da sie in RADN aktuell nicht enthalten sind:
- zweigleisige Strecke mit Einrichtung für Einspurbetrieb und quittungspflichtiger Verständigung des LF für Fahrt auf dem rechten Gleis
- zweigleisige Strecke ohne Einrichtung für Einspurbetrieb

**Comment by rawi-coding** [comment]
@EverheardofUX @StephanieFrancke @marcdettwiler Fürs Testing könnt ihr folgende Zugnummern verwenden:

- Hauptsignale: T9999
- Streckenausrüstung: T1, T9999
- Bahnhofsgeschwindigkeiten: T8, T9999
- Kurven: T9999

**Comment by marcdettwiler** [comment]
Hallo @StephanieFrancke 
Ich habe die Story getestet. Aus meiner Sicht ist die örtliche Geschwindigkeit im falschen Bereich vermerkt. Dies ist ggf. auf das unklare Design zurückzuführen. Ist das richtig?
Gruss Marc

**Comment by StephanieFrancke** [comment]
> Hallo [@StephanieFrancke](https://github.com/StephanieFrancke) Ich habe die Story getestet. Aus meiner Sicht ist die örtliche Geschwindigkeit im falschen Bereich vermerkt. Dies ist ggf. auf das unklare Design zurückzuführen. Ist das richtig? Die Prüfung der Gleisgenauen Geschwindigkeiten können wir aktuell nicht prüfen. Bitte prüfe, ob die Darstellung der Bahnhofsgeschwindigkeiten korrekt ist. Gruss Marc

Hoi @marcdettwiler 
Die Kurvengeschwindigkeit und Bahnhofsgeschwindigkeit wird gemäss aktuellem Entwicklungsstand im OG angezeigt. Evtl. sind Korrekturen noch nicht released. Hast du noch weitere örtliche Geschwindigkeiten gesehen, die falsch angezeigt werden? 

@rawi-coding: Wurde bereits alles von dieser Story released? ich denke ein Teil fehlt noch und kommt dann heute/morgen, richtig?

**Comment by rawi-coding** [comment]
Guten Morgen @StephanieFrancke @marcdettwiler. Ja genau, die Korrekturen werden erst im Release von dieser Woche kommen. Ich bin aktuell noch die Korrektur für den Klammerbahnhof am abschliessen, danach wird der Release mit allen Änderungen kommen.

**Comment by StephanieFrancke** [comment]
BA Testing done.

Folgende Elemente sind nicht in den Testdaten vorhanden oder nicht umgesetzt:
- Streckenausrüstung und Systemübergänge
-- zweigleisige Strecke mit Einrichtung für Einspurbetrieb
-- Strecke mit FSS im erweiterten Geschwindigkeitsbereich. «Reversing» nicht möglich
- Bahnhofsgeschwindigkeiten und abgestufte Geschwindigkeiten
-- Gleisspezifische oder gleisgruppenspezifische Geschwindigkeiten (unabhängig davon, ob sie befahren werden)
